# Generated by Django 5.2.7 on 2025-11-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default=1234, max_length=128),
            preserve_default=False,
        ),
    ]
