# Generated by Django 5.2.7 on 2025-11-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tasks', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
